# Schema for the configuration files of the ECC Cookie Consent Tracker module.
ecc_cct.settings:
  type: config_object
  label: 'ECC Cookie Consent Tracker settings'
  mapping:
    enable:
      type: string
      label: 'enable'
