<?php


/**
 * Implements hook_google_tag_snippets_alter().
 */
function ecc_cookie_compliance_google_tag_snippets_alter(array &$snippets) {
    // Only add the script snippet if cookie compliance has been agreed.
    $snippets['script'] = 'if (document.cookie.includes(\'analytics_cookies\')){ ' . $snippets['script'] . '}';
    $snippets['noscript'] = '';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ecc_cookie_compliance_preprocess_field(&$variables) {
  $formatter = $variables["element"]["#formatter"];
  if ($formatter === 'oembed') {
    _cookies_video_media_oembed_handler($variables);
  }
}


/**
 * Handling oembed field formatters.
 *
 * @param array $variables
 *   Field template variables (s. cookies_video_preprocess_field()).
 */
function _cookies_video_media_oembed_handler(array &$variables) {
  $formatter = $variables["element"]["#formatter"];
  $cookie_name = 'cookie-agreed-categories';
  $cookie_categories_values = json_decode($_COOKIE[$cookie_name]);
  if(!isset($_COOKIE[$cookie_name]) || isset($_COOKIE[$cookie_name]) && !in_array("marketing_cookies", $cookie_categories_values)) {
    /** @var \Drupal\Core\Field\FieldItemList $field_item */
    $field_item = $variables['element']['#items'];
    $field_value = $field_item->getValue();
    if (isset($field_value) && !empty($field_value)) {
      $field_value = reset($field_value);
      $video_src = $field_value['value'];
    }
    foreach ($variables["items"] as &$item) {
      switch ($formatter) {
        case 'oembed':
          $item["content"]["#attributes"]['src'] = $video_src;
          _cookies_video_preprocess_field_item_oembed($item);
          break;

        default:
      }

      // Attach library.
      if (!isset($item["content"]["#attached"])) {
        $item["content"]["#attached"] = ["library" => []];
      }
      if (!isset($item["content"]["#attached"]["library"])) {
        $item["content"]["#attached"]["library"] = [];
      }
    }
  }
}

/**
 * Handling field_item from oembed formatter.
 */
function _cookies_video_preprocess_field_item_oembed(&$item) {
  // Move src to href.
  $src = $item["content"]["#attributes"]["src"];
  $title = $item["content"]["#attributes"]["title"];
  $item["content"]["#attributes"] = [];

  $item["content"]["#tag"] = "a";
  $item["content"]["#attributes"]["href"] = $src;
  $item["content"]["#attributes"]["title"] = $title;
  $item["content"]["#attributes"]["target"] = "_blank";
  $item["content"]["#value"] = $title;

  // Set marker class.
  if (!isset($item["content"]["#attributes"]["class"]) || !is_array($item["content"]["#attributes"]["class"])) {
    $item["content"]["#attributes"]["class"] = [];
  }
  $item["content"]["#attributes"]["class"][] = 'cookies-video';
}
