/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function setupCookieSettingsBlock($, Drupal) {
  Drupal.behaviors.activateCookieSettingsForm = {
    attach: function attach(context) {
      var selectedCookieCategories = Drupal.eu_cookie_compliance.getAcceptedCategories();

      Drupal.eu_cookie_compliance.setAcceptedCategories(selectedCookieCategories);
      Drupal.eu_cookie_compliance.loadCategoryScripts(selectedCookieCategories);

      Drupal.eu_cookie_compliance.setPreferenceCheckboxes(selectedCookieCategories);
      Drupal.eu_cookie_compliance.attachSavePreferencesEvents();

      $("#eu-cookie-compliance-categories", context).once().each(displayCheckboxAsRadios);
    }
  };

  function displayCheckboxAsRadios() {
    setTimeout(function () {
      hideCheckboxes();
      clickRadiosBasedOnCheckboxStatus();
      setupUpClickHandlersForRadios();
      setupSaveSettingsFeedback();
    }, 300);
  }

  function hideCheckboxes() {
    $("[name=cookie-categories]:checkbox").hide();
  }

  function clickRadiosBasedOnCheckboxStatus() {
    $("[name=cookie-categories]:checked + .eu-cookie-compliance-categories--on :radio:not(:checked)").prop("checked", true);
    $("[name=cookie-categories]:not(:checked) + .eu-cookie-compliance-categories--on + .eu-cookie-compliance-categories--off :radio:not(:checked)").prop("checked", true);
  }

  function setupUpClickHandlersForRadios() {
    $(".eu-cookie-compliance-categories--on :radio, .eu-cookie-compliance-categories--off :radio").click(function (event) {
      var key = event.target.value;
      var relatedCheckboxId = "cookie-category-" + key;

      $("#" + relatedCheckboxId).click();
    });
  }

  function setupSaveSettingsFeedback() {
    $(".eu-cookie-compliance-save-preferences-button").click(function (e) {
      $("<p>" + Drupal.t("Saved") + "</p>").appendTo(e.target).hide(2000);
    });
  }
})(jQuery, Drupal);