#!/usr/bin/env bash

## Description: Run phpcbf to automatically fix some phpcs errors.
## Usage: phpcbf
## Example: "ddev phpcbf"

{
    /var/www/html/bin/phpcbf --standard=phpcbf-ecc.xml $*
} || {
    echo Fix the remaining issues manually.
}
