#!/usr/bin/env bash

## Description: Run phpunit in the web container to run phpunit tests.
## Usage: phpunit
## Example: "ddev phpunit"

export SYMFONY_DEPRECATIONS_HELPER=weak
/var/www/html/bin/phpunit -c /var/www/html/phpunit-ecc.xml --verbose $*
